/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRestRouteImport } from './routes/_dashboard/_rest'
import { Route as DashboardRestWorkflowsRouteImport } from './routes/_dashboard/_rest/workflows'
import { Route as DashboardRestExecutionsIndexRouteImport } from './routes/_dashboard/_rest/executions/index'
import { Route as DashboardRestCredentialsIndexRouteImport } from './routes/_dashboard/_rest/credentials/index'
import { Route as DashboardRestExecutionsExecutionsIdRouteImport } from './routes/_dashboard/_rest/executions/$executionsId'
import { Route as DashboardRestCredentialsCredentialsIdRouteImport } from './routes/_dashboard/_rest/credentials/$credentialsId'
import { Route as DashboardEditorWorkflowsWorkflowsIdRouteImport } from './routes/_dashboard/_editor/workflows/$workflowsId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRestRoute = DashboardRestRouteImport.update({
  id: '/_rest',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRestWorkflowsRoute = DashboardRestWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => DashboardRestRoute,
} as any)
const DashboardRestExecutionsIndexRoute =
  DashboardRestExecutionsIndexRouteImport.update({
    id: '/executions/',
    path: '/executions/',
    getParentRoute: () => DashboardRestRoute,
  } as any)
const DashboardRestCredentialsIndexRoute =
  DashboardRestCredentialsIndexRouteImport.update({
    id: '/credentials/',
    path: '/credentials/',
    getParentRoute: () => DashboardRestRoute,
  } as any)
const DashboardRestExecutionsExecutionsIdRoute =
  DashboardRestExecutionsExecutionsIdRouteImport.update({
    id: '/executions/$executionsId',
    path: '/executions/$executionsId',
    getParentRoute: () => DashboardRestRoute,
  } as any)
const DashboardRestCredentialsCredentialsIdRoute =
  DashboardRestCredentialsCredentialsIdRouteImport.update({
    id: '/credentials/$credentialsId',
    path: '/credentials/$credentialsId',
    getParentRoute: () => DashboardRestRoute,
  } as any)
const DashboardEditorWorkflowsWorkflowsIdRoute =
  DashboardEditorWorkflowsWorkflowsIdRouteImport.update({
    id: '/_editor/workflows/$workflowsId',
    path: '/workflows/$workflowsId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workflows': typeof DashboardRestWorkflowsRoute
  '/workflows/$workflowsId': typeof DashboardEditorWorkflowsWorkflowsIdRoute
  '/credentials/$credentialsId': typeof DashboardRestCredentialsCredentialsIdRoute
  '/executions/$executionsId': typeof DashboardRestExecutionsExecutionsIdRoute
  '/credentials': typeof DashboardRestCredentialsIndexRoute
  '/executions': typeof DashboardRestExecutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workflows': typeof DashboardRestWorkflowsRoute
  '/workflows/$workflowsId': typeof DashboardEditorWorkflowsWorkflowsIdRoute
  '/credentials/$credentialsId': typeof DashboardRestCredentialsCredentialsIdRoute
  '/executions/$executionsId': typeof DashboardRestExecutionsExecutionsIdRoute
  '/credentials': typeof DashboardRestCredentialsIndexRoute
  '/executions': typeof DashboardRestExecutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/_rest': typeof DashboardRestRouteWithChildren
  '/_dashboard/_rest/workflows': typeof DashboardRestWorkflowsRoute
  '/_dashboard/_editor/workflows/$workflowsId': typeof DashboardEditorWorkflowsWorkflowsIdRoute
  '/_dashboard/_rest/credentials/$credentialsId': typeof DashboardRestCredentialsCredentialsIdRoute
  '/_dashboard/_rest/executions/$executionsId': typeof DashboardRestExecutionsExecutionsIdRoute
  '/_dashboard/_rest/credentials/': typeof DashboardRestCredentialsIndexRoute
  '/_dashboard/_rest/executions/': typeof DashboardRestExecutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workflows'
    | '/workflows/$workflowsId'
    | '/credentials/$credentialsId'
    | '/executions/$executionsId'
    | '/credentials'
    | '/executions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workflows'
    | '/workflows/$workflowsId'
    | '/credentials/$credentialsId'
    | '/executions/$executionsId'
    | '/credentials'
    | '/executions'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/_dashboard/_rest'
    | '/_dashboard/_rest/workflows'
    | '/_dashboard/_editor/workflows/$workflowsId'
    | '/_dashboard/_rest/credentials/$credentialsId'
    | '/_dashboard/_rest/executions/$executionsId'
    | '/_dashboard/_rest/credentials/'
    | '/_dashboard/_rest/executions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_rest': {
      id: '/_dashboard/_rest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/_rest/workflows': {
      id: '/_dashboard/_rest/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof DashboardRestWorkflowsRouteImport
      parentRoute: typeof DashboardRestRoute
    }
    '/_dashboard/_rest/executions/': {
      id: '/_dashboard/_rest/executions/'
      path: '/executions'
      fullPath: '/executions'
      preLoaderRoute: typeof DashboardRestExecutionsIndexRouteImport
      parentRoute: typeof DashboardRestRoute
    }
    '/_dashboard/_rest/credentials/': {
      id: '/_dashboard/_rest/credentials/'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof DashboardRestCredentialsIndexRouteImport
      parentRoute: typeof DashboardRestRoute
    }
    '/_dashboard/_rest/executions/$executionsId': {
      id: '/_dashboard/_rest/executions/$executionsId'
      path: '/executions/$executionsId'
      fullPath: '/executions/$executionsId'
      preLoaderRoute: typeof DashboardRestExecutionsExecutionsIdRouteImport
      parentRoute: typeof DashboardRestRoute
    }
    '/_dashboard/_rest/credentials/$credentialsId': {
      id: '/_dashboard/_rest/credentials/$credentialsId'
      path: '/credentials/$credentialsId'
      fullPath: '/credentials/$credentialsId'
      preLoaderRoute: typeof DashboardRestCredentialsCredentialsIdRouteImport
      parentRoute: typeof DashboardRestRoute
    }
    '/_dashboard/_editor/workflows/$workflowsId': {
      id: '/_dashboard/_editor/workflows/$workflowsId'
      path: '/workflows/$workflowsId'
      fullPath: '/workflows/$workflowsId'
      preLoaderRoute: typeof DashboardEditorWorkflowsWorkflowsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRestRouteChildren {
  DashboardRestWorkflowsRoute: typeof DashboardRestWorkflowsRoute
  DashboardRestCredentialsCredentialsIdRoute: typeof DashboardRestCredentialsCredentialsIdRoute
  DashboardRestExecutionsExecutionsIdRoute: typeof DashboardRestExecutionsExecutionsIdRoute
  DashboardRestCredentialsIndexRoute: typeof DashboardRestCredentialsIndexRoute
  DashboardRestExecutionsIndexRoute: typeof DashboardRestExecutionsIndexRoute
}

const DashboardRestRouteChildren: DashboardRestRouteChildren = {
  DashboardRestWorkflowsRoute: DashboardRestWorkflowsRoute,
  DashboardRestCredentialsCredentialsIdRoute:
    DashboardRestCredentialsCredentialsIdRoute,
  DashboardRestExecutionsExecutionsIdRoute:
    DashboardRestExecutionsExecutionsIdRoute,
  DashboardRestCredentialsIndexRoute: DashboardRestCredentialsIndexRoute,
  DashboardRestExecutionsIndexRoute: DashboardRestExecutionsIndexRoute,
}

const DashboardRestRouteWithChildren = DashboardRestRoute._addFileChildren(
  DashboardRestRouteChildren,
)

interface DashboardRouteChildren {
  DashboardRestRoute: typeof DashboardRestRouteWithChildren
  DashboardEditorWorkflowsWorkflowsIdRoute: typeof DashboardEditorWorkflowsWorkflowsIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardRestRoute: DashboardRestRouteWithChildren,
  DashboardEditorWorkflowsWorkflowsIdRoute:
    DashboardEditorWorkflowsWorkflowsIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
